# Generated by Django 4.2.11 on 2024-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtype2', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=255)),
            ],
        ),
    ]
